language: node_js
node_js:
  - "8.11.4"
services: 
- postgres

script:
  - npm run build
  - npm run coverage

before_install:
- npm i -g babel-preset-env mocha chai babel-cli istanbul coveralls pg sequelize

before_script:
  - psql -c 'create database  clan;' -U postgres

after_script:
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info  && npm run clean