language: node_js
node_js:
  - "10.14.2"
services: 
- mongodb

script:
  - npm run build
  - npm run coverage

before_install:
- npm i -g babel-preset-env mocha chai babel-cli istanbul coveralls mongoose

after_script:
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info  && npm run clean